import { existsSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { homedir } from 'node:os';
import { join } from 'node:path';

const EXT_DIR = join(homedir(), '.locca', 'pi-extensions');
const EXT_FILE = join(EXT_DIR, 'strip-skills-from-prompt.js');

/**
 * Tiny pi extension shipped with locca. Strips the `<available_skills>` XML
 * block (and its 3-line preamble) that pi injects into the system prompt,
 * saving 50–100 tokens per installed skill on small local models.
 *
 * Skill loading itself stays intact, so `/skill:<name>` slash commands still
 * resolve — only the model-facing description disappears.
 *
 * Pi's loader (jiti) accepts both `.ts` and `.js`; we ship `.js` so locca
 * doesn't depend on pi's TS toolchain being healthy.
 *
 * The block format comes from pi's `formatSkillsForPrompt` in
 * @mariozechner/pi-coding-agent (core/skills.ts) — see:
 * https://github.com/badlogic/pi-mono/blob/main/packages/coding-agent/src/core/skills.ts
 */
const EXT_SOURCE = `// Generated by locca. Do not edit — locca rewrites this file on launch.
// Strips pi's <available_skills> block from the system prompt so descriptions
// don't cost context on small local models. /skill:<name> still works.

const SKILLS_BLOCK = /\\n\\nThe following skills provide specialized instructions[\\s\\S]*?<\\/available_skills>/;

export default function stripSkillsFromPrompt(pi) {
  pi.on("before_agent_start", (event) => {
    const stripped = event.systemPrompt.replace(SKILLS_BLOCK, "");
    if (stripped === event.systemPrompt) return;
    return { systemPrompt: stripped };
  });
}
`;

/**
 * Materialize the extension at `~/.locca/pi-extensions/strip-skills-from-prompt.js`
 * if missing or out of date, and return its absolute path. Cheap enough to call
 * on every `locca pi` launch — read+compare beats spurious writes.
 */
export function ensureStripSkillsExtension(): string {
  mkdirSync(EXT_DIR, { recursive: true });
  let needsWrite = true;
  if (existsSync(EXT_FILE)) {
    try {
      needsWrite = readFileSync(EXT_FILE, 'utf8') !== EXT_SOURCE;
    } catch {
      needsWrite = true;
    }
  }
  if (needsWrite) writeFileSync(EXT_FILE, EXT_SOURCE);
  return EXT_FILE;
}
